import { test } from 'node:test';
import assert from 'node:assert/strict';
import { ProviderHttp,number as providerNumber } from '../src/modules/integrations/http';
import { CommerceConnector } from '../src/modules/integrations/connectors/commerce';
import { AdvertisingConnector } from '../src/modules/integrations/connectors/advertising';
import { AnalyticsConnector } from '../src/modules/integrations/connectors/analytics';
import { SearchConsoleConnector } from '../src/modules/integrations/connectors/search-console';
import { summarizeSource,rangeSchema } from '../src/modules/integrations/types';
import { IntegrationService,type IntegrationStore } from '../src/modules/integrations/service';
import { ExecutiveAgent } from '../src/modules/ai/executive';
const range={from:'2026-09-01',to:'2026-09-06'},credentials={accessToken:'private-test-token-123',accountId:'1234'},versions={meta:'v25.0',googleAds:'v24'};
const response=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
test('Negative attributed value adjustments are preserved while negative spend is rejected',()=>{assert.equal(providerNumber('-12.5',true),-12.5);assert.throws(()=>providerNumber('-12.5'),/INVALID_RESPONSE/);});
test('Salla pagination follows page numbers, sanitizes PII and separates currencies',async()=>{const pages:string[]=[];const http=new ProviderHttp(async(url,init)=>{const parsed=new URL(url);pages.push(parsed.searchParams.get('page')!);assert.equal((init?.headers as Record<string,string>).Authorization,'Bearer '+credentials.accessToken);assert.equal(init?.redirect,'error');const page=Number(parsed.searchParams.get('page'));return response({success:true,data:[{id:page,total:{amount:12.5,currency:page===1?'SAR':'USD'},date:{date:'2026-09-03 12:00:00',timezone:'Asia/Riyadh'},customer:{email:'private@example.com'}}],pagination:{totalPages:2,links:{next:'http://evil.test/steal'}}});});const result=await new CommerceConnector('salla',credentials,http).fetchMetrics(range);assert.deepEqual(pages,['1','2']);assert.equal(result.records,2);assert.equal(result.rows.length,2);assert.equal(result.rows[0].grossSales,12.5);assert.ok(!JSON.stringify(result).includes('private@example.com'));assert.equal(summarizeSource('salla',result,new Date().toISOString()).length,2);});
test('Salla fetchCatalog paginates products and customers, derives currency from price, and leaves missing stats undefined not zero',async()=>{
  const calls:string[]=[];
  const http=new ProviderHttp(async(url,init)=>{calls.push(url);assert.equal((init?.headers as Record<string,string>).Authorization,'Bearer '+credentials.accessToken);
    if(url.includes('/products'))return response({success:true,data:[{id:1,name:'A',sku:'A1',price:{amount:100,currency:'SAR'},sale_price:{amount:80,currency:'SAR'},quantity:2,status:'sale'},{id:2,name:'B',price:{amount:50,currency:'SAR'},status:'sale'}],pagination:{totalPages:1}});
    return response({success:true,data:[{id:9,first_name:'Sara',last_name:'A',email:'sara@example.com',mobile:'0500000000'},{id:10,first_name:'Omar',orders_count:3,total_spent:{amount:450,currency:'SAR'}}],pagination:{totalPages:1}});
  });
  const result=await new CommerceConnector('salla',credentials,http).fetchCatalog();
  assert.ok(calls.some(u=>u.includes('/products'))&&calls.some(u=>u.includes('/customers')));
  assert.equal(result.currency,'SAR');
  assert.equal(result.products.length,2);
  assert.equal(result.products[0].salePrice,80);
  assert.equal(result.products[1].inventoryQuantity,undefined); // no quantity field supplied — unknown, not zero
  assert.equal(result.customers.length,2);
  assert.equal(result.customers[0].totalOrders,undefined); // Sara has no orders_count — unknown, not zero
  assert.equal(result.customers[1].totalSpent,450);
  assert.ok(JSON.stringify(result).includes('sara@example.com')); // customer contact is kept here, unlike order-level PII stripped from fetchMetrics
});
test('Salla fetchCatalog is the only catalog capability; Zid throws NOT_SUPPORTED',async()=>{await assert.rejects(()=>new CommerceConnector('zid',{...credentials,authorizationToken:'zid-app-token'}).fetchCatalog(),/NOT_SUPPORTED/);});
test('Zid sends both tokens and normalizes documented order fields',async()=>{const http=new ProviderHttp(async(_url,init)=>{assert.equal((init?.headers as Record<string,string>)['X-Manager-Token'],credentials.accessToken);assert.equal((init?.headers as Record<string,string>).Authorization,'zid-app-token');return response({orders:[{id:1,created_at:'2026-09-02 09:00:00',currency_code:'SAR',order_total:'129.25'}],total_order_count:1});});const result=await new CommerceConnector('zid',{...credentials,authorizationToken:'zid-app-token'},http).fetchMetrics(range);assert.equal(result.rows[0].grossSales,129.25);assert.equal(result.rows[0].orders,1);});
test('Meta cursors cannot redirect bearer credentials and account currency is preserved',async()=>{const calls:string[]=[];const http=new ProviderHttp(async url=>{calls.push(url);if(!url.includes('/insights'))return response({currency:'USD',timezone_name:'America/New_York'});const second=new URL(url).searchParams.has('after');return response({data:[{date_start:second?'2026-09-02':'2026-09-01',spend:'21.45',impressions:'1000',clicks:'50'}],...(second?{}:{paging:{next:'https://attacker.test/',cursors:{after:'next-cursor'}}})});});const result=await new AdvertisingConnector('meta',credentials,versions,http).fetchMetrics(range);assert.equal(result.rows.length,2);assert.ok(calls.every(url=>new URL(url).hostname==='graph.facebook.com'));assert.equal(result.rows[0].currency,'USD');assert.equal(result.rows[0].adSpend,21.45);});
test('TikTok validates provider success envelope and parses daily basic report',async()=>{const http=new ProviderHttp(async url=>url.includes('/advertiser/info/')?response({code:0,data:{list:[{currency:'SAR',timezone:'Asia/Riyadh'}]}}):response({code:0,data:{list:[{dimensions:{stat_time_day:'2026-09-02 00:00:00'},metrics:{spend:'20',impressions:'200',clicks:'4'}}],page_info:{total_page:1}}}));const result=await new AdvertisingConnector('tiktok',credentials,versions,http).fetchMetrics(range);assert.equal(result.rows[0].adSpend,20);assert.equal(result.rows[0].date,'2026-09-02');await assert.rejects(()=>new AdvertisingConnector('tiktok',credentials,versions,new ProviderHttp(async()=>response({code:40100}))).testConnection(),/AUTH_EXPIRED/);});
test('Google Ads converts micros, uses developer header and preserves attribution separately',async()=>{const http=new ProviderHttp(async(_url,init)=>{assert.equal((init?.headers as Record<string,string>)['developer-token'],'developer');const query=JSON.parse(String(init?.body)).query;if(query.includes('customer.currency_code'))return response({results:[{customer:{currencyCode:'SAR',timeZone:'Asia/Riyadh'}}]});return response({results:[{segments:{date:'2026-09-03'},metrics:{costMicros:'12345678',impressions:'200',clicks:'9',conversions:1.5,conversionsValue:50}}]});});const result=await new AdvertisingConnector('google-ads',{...credentials,developerToken:'developer'},versions,http).fetchMetrics(range);assert.equal(result.rows[0].adSpend,12.345678);assert.equal(result.rows[0].attributedRevenue,50);assert.equal(result.rows[0].grossSales,undefined);});
test('Search Console maps clicks/impressions per day, has no currency and rejects a site URL that returns the row cap',async()=>{
  const http=new ProviderHttp(async(url,init)=>{assert.ok(url.includes('/sites/'+encodeURIComponent('https://inatural.sa/')+'/searchAnalytics/query'));assert.equal((init?.headers as Record<string,string>).Authorization,'Bearer '+credentials.accessToken);
    return response({rows:[{keys:['2026-09-01'],clicks:12,impressions:340,ctr:0.035,position:8.2}]});});
  const result=await new SearchConsoleConnector({...credentials,accountId:'https://inatural.sa/'},http).fetchMetrics(range);
  assert.equal(result.rows[0].clicks,12);assert.equal(result.rows[0].impressions,340);assert.equal(result.rows[0].currency,'SAR');
  assert.ok(result.notes.some(n=>n.includes('no currency')));
  await assert.rejects(()=>new SearchConsoleConnector({...credentials,accountId:'https://inatural.sa/'},new ProviderHttp(async()=>response({rows:Array.from({length:1000},(_,i)=>({keys:[`2026-09-${(i%28+1).toString().padStart(2,'0')}`],clicks:1,impressions:1}))}))).fetchMetrics(range),/IMPORT_LIMIT/);
});
test('GA4 maps requested metrics and exposes thresholding',async()=>{const http=new ProviderHttp(async(_url,init)=>{const body=JSON.parse(String(init?.body));assert.equal(body.currencyCode,'SAR');return response({rows:[{dimensionValues:[{value:'20260904'}],metricValues:[{value:'100'},{value:'3'},{value:'600'}]}],rowCount:1,metadata:{timeZone:'Asia/Riyadh',subjectToThresholding:true}});});const result=await new AnalyticsConnector(credentials,http).fetchMetrics(range);assert.equal(result.rows[0].sessions,100);assert.equal(result.rows[0].conversions,3);assert.equal(result.rows[0].attributedRevenue,600);assert.ok(result.notes.some(n=>n.includes('thresholds')));});
test('HTTP rejects unknown origins before transport and limits retries without leaking provider messages',async()=>{let attempts=0;const http=new ProviderHttp(async()=>{attempts++;return response({error:'private token leaked by vendor'},429);},async()=>{});await assert.rejects(()=>http.json('https://evil.test'),/CONFIGURATION/);assert.equal(attempts,0);await assert.rejects(()=>http.json('https://api.salla.dev/admin/v2/orders'),/^ConnectorError: RATE_LIMITED$/);assert.equal(attempts,3);});
test('Invalid and duplicate provider rows abort the complete import',async()=>{await assert.rejects(()=>new CommerceConnector('salla',credentials,new ProviderHttp(async()=>response({success:true,data:[{id:1,total:{amount:'bad',currency:'SAR'},date:{date:'2026-09-01 00:00:00',timezone:'Asia/Riyadh'}}],pagination:{totalPages:1}}))).fetchMetrics(range),/INVALID_RESPONSE/);assert.equal(rangeSchema.safeParse({from:'2026-01-01',to:'2026-04-01'}).success,false);});
test('IntegrationService composes with a foreign host and authorizes before making provider calls',async()=>{const events:string[]=[];const store={authorize:async()=>{events.push('authorize');},connect:async()=>{events.push('persist');}} as unknown as IntegrationStore;const service=new IntegrationService(store,()=>({provider:'salla',testConnection:async()=>{events.push('verify');},fetchMetrics:async()=>({rows:[],records:0,timezone:'UTC',notes:[]})}),{enqueue:async()=>{}});await service.connect('business',{userId:'user',organizationId:'org',role:'owner'},'salla',credentials);assert.deepEqual(events,['authorize','verify','persist']);});
test('AI can analyze synchronized sources without inventing manual ledger values',async()=>{let observed='';const agent=new ExecutiveAgent({generate:async input=>{observed=input.context;return 'analysis';}});await agent.respond({rows:[],days:7,question:'Review sources',language:'en',sources:[{provider:'meta',from:range.from,to:range.to,currency:'SAR',timezone:'Asia/Riyadh',observedDays:1,lastSync:new Date().toISOString(),totals:{adSpend:50},notes:[]}]});assert.equal(JSON.parse(observed).connectedSources[0].totals.adSpend,50);assert.match(JSON.parse(observed).sourcePolicy,/Missing costs are unknown/);});
