'use client';

import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Activity, ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, BriefcaseBusiness, ChartNoAxesCombined, Check, ChevronDown, CircleHelp, Download, Globe2, LayoutDashboard, Menu, MessageSquare, Moon, Plus, Search, Send, Settings2, ShieldCheck, Sparkles, Sun, TrendingUp, Wallet, X, Plug, FileText, LogOut, LoaderCircle, TriangleAlert, Database, Building2, Target } from 'lucide-react';
import { Button } from './ui/button';
import { aggregate, contextFor, health, metricSchema, periods, reportText, type DailyMetric } from '@/modules/metrics/engine';
import { demoBusinesses, demoMetrics } from '@/modules/metrics/demo';
import { integrationCatalog } from '@/modules/integrations/contracts';
import { supabase } from '@/lib/supabase-browser';
import { detectMetricAlerts } from '@/modules/analytics/service';
import { IntegrationHub,SourceInsights } from './integration-hub';
import type { SourceSummary } from '@/modules/integrations/types';
import { OperationsHub } from './operations-hub';
import type { ExecutiveBrief } from '@/modules/ai/tools';

function GoogleIcon(){return <svg width="16" height="16" viewBox="0 0 18 18" aria-hidden="true"><path fill="#4285F4" d="M17.64 9.2c0-.64-.06-1.25-.16-1.84H9v3.48h4.84a4.14 4.14 0 0 1-1.8 2.72v2.26h2.91c1.7-1.57 2.69-3.87 2.69-6.62Z"/><path fill="#34A853" d="M9 18c2.43 0 4.47-.8 5.96-2.18l-2.91-2.26c-.81.54-1.84.86-3.05.86-2.34 0-4.33-1.58-5.04-3.71H.96v2.33A9 9 0 0 0 9 18Z"/><path fill="#FBBC05" d="M3.96 10.71A5.4 5.4 0 0 1 3.68 9c0-.59.1-1.17.28-1.71V4.96H.96A9 9 0 0 0 0 9c0 1.45.35 2.83.96 4.04l3-2.33Z"/><path fill="#EA4335" d="M9 3.58c1.32 0 2.51.46 3.44 1.35l2.58-2.58C13.46.89 11.43 0 9 0A9 9 0 0 0 .96 4.96l3 2.33C4.67 5.16 6.66 3.58 9 3.58Z"/></svg>;}
const TOOL_LABELS:Record<string,{en:string;ar:string}> = {
  getBusinessOverview:{en:'Overview',ar:'نظرة عامة'},
  getRevenueMetrics:{en:'Revenue',ar:'الإيرادات'},
  getOrdersMetrics:{en:'Orders',ar:'الطلبات'},
  getInventoryAlerts:{en:'Inventory',ar:'المخزون'},
  getCustomerMetrics:{en:'Customers',ar:'العملاء'},
  getDataFreshness:{en:'Data freshness',ar:'حداثة البيانات'},
  getTopProducts:{en:'Top products',ar:'أفضل المنتجات'},
};
type Business = {id:string;name:string};
type Report = {id:string;title:string;content:string};
type Page = 'overview'|'executive'|'businesses'|'sales'|'marketing'|'finance'|'analytics'|'integrations'|'reports'|'alerts'|'settings'|'automation'|'tasks';
type Modal = 'data'|'business'|'login'|'report'|'integration'|null;
const nav = [
  {id:'overview',en:'Overview',ar:'نظرة عامة',icon:LayoutDashboard},
  {id:'executive',en:'AI Executive',ar:'المدير الذكي',icon:Sparkles},
  {id:'businesses',en:'Businesses',ar:'الأعمال',icon:Building2},
  {id:'sales',en:'Sales',ar:'المبيعات',icon:TrendingUp},
  {id:'marketing',en:'Marketing',ar:'التسويق',icon:Target},
  {id:'finance',en:'Finance',ar:'المالية',icon:Wallet},
  {id:'analytics',en:'Analytics',ar:'التحليلات',icon:ChartNoAxesCombined},
  {id:'integrations',en:'Integrations',ar:'التكاملات',icon:Plug},
  {id:'reports',en:'Reports',ar:'التقارير',icon:FileText},
  {id:'automation',en:'Automation',ar:'الأتمتة',icon:Activity},
  {id:'tasks',en:'Tasks',ar:'المهام',icon:Check},
  {id:'alerts',en:'Alerts',ar:'التنبيهات',icon:Bell},
] as const;
const fmt = (n: number|null, decimals=0) => n === null ? '—' : n.toLocaleString('en-US',{maximumFractionDigits:decimals});

function TrendChart({rows,ar}:{rows:DailyMetric[];ar:boolean}) {
  const [hover,setHover] = useState<number|null>(null);
  if (!rows.length) return <div className="empty-chart">{ar?'أضف بيانات يومية لعرض الاتجاهات':'Add daily metrics to see your performance trend.'}</div>;
  const max = Math.max(...rows.map(r=>r.revenue),1)*1.18;
  const x = (i:number) => 54 + i / Math.max(rows.length-1,1)*646;
  const y = (v:number) => 190 - v/max*158;
  const line = (key:'revenue'|'adSpend') => rows.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(r[key])}`).join(' ');
  return <div className="chart-wrap"><svg viewBox="0 0 730 230" role="img" aria-label={ar?'الإيرادات والإنفاق الإعلاني':'Revenue and advertising spend over time'}>
    <defs><linearGradient id="revenue-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#4e77ef" stopOpacity=".16"/><stop offset="100%" stopColor="#4e77ef" stopOpacity="0"/></linearGradient></defs>
    {[0,1,2,3].map(i=><g key={i}><line x1="54" y1={32+i*52.6} x2="706" y2={32+i*52.6} stroke="var(--border)" strokeDasharray="3 5"/><text x="3" y={36+i*52.6} className="axis-label">{fmt(max*(1-i/3)/1000,1)}k</text></g>)}
    <path d={`${line('revenue')} L ${x(rows.length-1)} 190 L 54 190 Z`} fill="url(#revenue-fill)"/>
    <path d={line('revenue')} fill="none" stroke="#5278ed" strokeWidth="2.8" strokeLinejoin="round"/>
    <path d={line('adSpend')} fill="none" stroke="#41b7a3" strokeWidth="2" strokeDasharray="5 5"/>
    {rows.map((r,i)=><g key={r.date} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)}><rect x={x(i)-Math.max(5,320/rows.length)} y="20" width={Math.max(10,640/rows.length)} height="176" fill="transparent"/>{(i===0||i===rows.length-1||i%Math.max(1,Math.floor(rows.length/5))===0)&&<text x={x(i)} y="218" textAnchor="middle" className="axis-label">{r.date.slice(5).replace('-','/')}</text>}</g>)}
    {hover!==null&&<g><line x1={x(hover)} x2={x(hover)} y1="22" y2="190" stroke="#8d9fc9" strokeDasharray="3 3"/><circle cx={x(hover)} cy={y(rows[hover].revenue)} r="5" fill="#5278ed" stroke="white" strokeWidth="2"/><rect x={Math.min(x(hover),560)} y="3" width="143" height="25" rx="5" fill="var(--text)"/><text x={Math.min(x(hover),560)+8} y="20" fill="var(--surface)" fontSize="11">SAR {fmt(rows[hover].revenue)} · {rows[hover].date.slice(5)}</text></g>}
  </svg></div>;
}

export function ExecutiveWorkspace() {
  const [ar,setAr] = useState(false), [dark,setDark] = useState(false), [page,setPage] = useState<Page>('overview');
  const [businesses,setBusinesses] = useState<Business[]>(demoBusinesses), [businessId,setBusinessId] = useState('demo-natural');
  const [rows,setRows] = useState<DailyMetric[]>(demoMetrics('demo-natural')), [days,setDays] = useState<1|7|30>(7);
  const [demo,setDemo] = useState(true), [token,setToken] = useState(''), [busy,setBusy] = useState(false), [loading,setLoading] = useState(false);
  const [modal,setModal] = useState<Modal>(null), [notice,setNotice] = useState(''), [mobile,setMobile] = useState(false);
  const [query,setQuery] = useState(''), [messages,setMessages] = useState<{role:string;text:string;toolsUsed?:string[]}[]>([]), [reports,setReports] = useState<Report[]>([]), [activeReport,setActiveReport] = useState<Report|null>(null);
  const [provider,setProvider] = useState('Salla'), [filter,setFilter] = useState('All'), [search,setSearch] = useState('');
  const [ready,setReady] = useState(false);
  const [sourceData,setSourceData]=useState<SourceSummary[]>([]);
  const [brief,setBrief]=useState<ExecutiveBrief|null>(null), [briefLoading,setBriefLoading]=useState(false), [briefError,setBriefError]=useState('');
  const [pendingSelection,setPendingSelection]=useState<{provider:string;state:string}|null>(null);
  const generation = useRef(0);
  const t = (en:string,arabic:string) => ar?arabic:en;
  const business = businesses.find(b=>b.id===businessId);
  const p = periods(rows,days), metrics = aggregate(p.current), h = health(p.current), context = contextFor(rows,days);
  const alertLabels={
    'negative-profit':t('Entered costs exceed revenue. Review your cost structure.','التكاليف المدخلة تتجاوز الإيرادات. راجع هيكل التكاليف.'),
    'low-roas':t('Blended ROAS is below 2x. Review channel-level performance.','العائد المدمج أقل من 2. راجع أداء القنوات.'),
    'missing-days':t('Some days are missing from this reporting period.','توجد أيام ناقصة في الفترة المحددة.'),
    'no-data':t('No business data available. Add your first daily record.','لا توجد بيانات. أضف أول سجل يومي.'),
  };
  const alerts=detectMetricAlerts(rows,days).map(alert=>alertLabels[alert.code]);

  useEffect(()=>{ try {setAr(localStorage.getItem('dms-language')==='ar');setDark(localStorage.getItem('dms-theme')==='dark');}catch{} setReady(true); if(!supabase)return; supabase.auth.getSession().then(({data})=>{if(data.session)setToken(data.session.access_token);}); const {data}=supabase.auth.onAuthStateChange((_event,session)=>setToken(session?.access_token??''));return()=>data.subscription.unsubscribe(); },[]);
  useEffect(()=>{if(!ready)return;document.documentElement.lang=ar?'ar':'en';document.documentElement.dir=ar?'rtl':'ltr';document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('dms-language',ar?'ar':'en');localStorage.setItem('dms-theme',dark?'dark':'light');}catch{}},[ar,dark,ready]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search),result=params.get('integration_result');if(result==='select_account'){setPendingSelection({provider:params.get('provider')??'',state:params.get('state')??''});setPage('integrations');}else if(result){setNotice(result==='connected'?t('Account connected. Open your workspace to synchronize.','تم ربط الحساب. افتح مساحة أعمالك للمزامنة.'):t('Authorization was not completed. Try connecting again.','لم يكتمل التفويض. حاول الربط مجددًا.'));}if(result)window.history.replaceState({},'',window.location.pathname);},[]);
  useEffect(()=>{let active=true;setSourceData([]);if(demo||!token||!businessId)return;api(`integrations?businessId=${encodeURIComponent(businessId)}`).then(result=>{if(active)setSourceData(result.summaries);}).catch(()=>{});return()=>{active=false;};},[businessId,demo,token,page]);
  useEffect(()=>{setBrief(null);setBriefError('');if(page!=='executive'||demo||!token||!businessId)return;let active=true;setBriefLoading(true);api(`ai/executive-brief?businessId=${encodeURIComponent(businessId)}&days=${days}&language=${ar?'ar':'en'}`).then(result=>{if(active)setBrief(result);}).catch(e=>{if(active)setBriefError((e as Error).message);}).finally(()=>{if(active)setBriefLoading(false);});return()=>{active=false;};},[page,businessId,demo,token,days,ar]);
  useEffect(()=>{if(!modal)return; const previous=document.activeElement as HTMLElement|null; const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLElement>('.modal button:not(:disabled), .modal input, .modal select, .modal textarea'));if(!items.length)return;const first=items[0],last=items.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler); const timer=setTimeout(()=>document.querySelector<HTMLElement>('.modal input, .modal button')?.focus(),0); return()=>{clearTimeout(timer);document.removeEventListener('keydown',handler);previous?.focus();};},[modal]);

  async function api(path:string, data?:unknown, authToken=token) { const response=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:`Bearer ${authToken}`},...(data?{body:JSON.stringify(data)}:{})});const json=await response.json();if(!response.ok)throw new Error(json.error??'Request failed');return json; }
  async function openWorkspace() { if(!token){setModal('login');return;}setBusy(true);try{const result=await api('workspace');setBusinesses(result.businesses);setBusinessId(result.businesses[0]?.id??'');setDemo(false);setMessages([]);}catch(e){setNotice((e as Error).message);setModal('business');}finally{setBusy(false);} }
  useEffect(()=>{const version=++generation.current;setMessages([]);setReports([]);if(demo){try{const saved=localStorage.getItem(`dms-metrics-${businessId}`);setRows(saved?JSON.parse(saved).map((r:unknown)=>metricSchema.parse(r)):demoMetrics(businessId));const savedReports=localStorage.getItem(`dms-reports-${businessId}`);setReports(savedReports?JSON.parse(savedReports):[]);}catch{setRows(demoMetrics(businessId));}return;}setRows([]);if(!businessId||!token)return;setLoading(true);Promise.all([api(`metrics?businessId=${encodeURIComponent(businessId)}`),api(`reports?businessId=${encodeURIComponent(businessId)}`)]).then(([m,r])=>{if(version===generation.current){setRows(m);setReports(r);}}).catch(e=>{if(version===generation.current)setNotice(e.message);}).finally(()=>{if(version===generation.current)setLoading(false);});/* API captures current session. */ // eslint-disable-next-line react-hooks/exhaustive-deps
  },[businessId,demo,token]);
  async function saveData(e:FormEvent<HTMLFormElement>) {e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{const metric=metricSchema.parse({date:form.get('date'),...Object.fromEntries(['revenue','orders','adSpend','cogs','expenses','leads','sessions'].map(k=>[k,Number(form.get(k))]))});const updated=[...rows.filter(r=>r.date!==metric.date),metric].sort((a,b)=>a.date.localeCompare(b.date));if(demo)localStorage.setItem(`dms-metrics-${businessId}`,JSON.stringify(updated));else await api('metrics',{businessId,metric});setRows(updated);setModal(null);setNotice(t('Daily record saved. Metrics recalculated.','تم حفظ السجل وإعادة حساب المؤشرات.'));}catch(e){setNotice((e as Error).message);}finally{setBusy(false);} }
  async function saveBusiness(e:FormEvent<HTMLFormElement>) {e.preventDefault();const name=String(new FormData(e.currentTarget).get('name')??'').trim();if(name.length<2)return;setBusy(true);try{if(demo&&!token){setNotice(t('Sign in to create a persistent business workspace.','سجل الدخول لإنشاء مساحة أعمال محفوظة.'));setModal('login');return;}const item=await api('workspace',{name,provision:demo});const result=await api('workspace');setBusinesses(result.businesses);setBusinessId(item.id);setDemo(false);setModal(null);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);} }
  async function login(e:FormEvent<HTMLFormElement>) {e.preventDefault();if(!supabase){setNotice(t('Configure Supabase in .env.local to enable sign in.','أضف إعدادات Supabase في .env.local لتفعيل الدخول.'));return;}const form=new FormData(e.currentTarget);setBusy(true);try{const {error}=await supabase.auth.signInWithOtp({email:String(form.get('email')),options:{emailRedirectTo:window.location.origin}});if(error)throw error;setNotice(t('Check your email for your secure sign-in link.','راجع بريدك للحصول على رابط الدخول.'));setModal(null);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);} }
  async function loginWithGoogle() {if(!supabase){setNotice(t('Configure Supabase in .env.local to enable sign in.','أضف إعدادات Supabase في .env.local لتفعيل الدخول.'));return;}setBusy(true);const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error){setNotice(error.message);setBusy(false);} }
  async function generateReport(ai=false) {if(demo&&!rows.length){setNotice(t('Add data first.','أضف البيانات أولًا.'));return;}if(demo&&ai){setNotice(t('AI reports require a signed-in workspace and configured AI provider.','تقارير AI تتطلب مساحة مسجلة ومزود ذكاء اصطناعي مهيأ.'));return;}setBusy(true);try{const report:Report=demo?{id:crypto.randomUUID(),title:`${days}-day Executive Report · ${p.end}`,content:reportText(rows,days,ar?'ar':'en')}:await api('reports',{businessId,days,language:ar?'ar':'en',ai});const updated=[report,...reports];if(demo)localStorage.setItem(`dms-reports-${businessId}`,JSON.stringify(updated));setReports(updated);setActiveReport(report);setModal('report');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);} }
  async function ask(question=query) {if(!question.trim()||busy)return;setQuery('');setMessages(m=>[...m,{role:'user',text:question}]);if(demo){setMessages(m=>[...m,{role:'assistant',text:t('You are exploring demo data. Live AI chat becomes available in your signed-in workspace once an AI provider is configured. Use “Generate report” for an actual calculated summary of these demo metrics.','أنت تستعرض بيانات تجريبية. تتاح المحادثة الفعلية داخل مساحة أعمالك بعد تهيئة مزود AI. استخدم «إنشاء تقرير» للحصول على ملخص حسابي للبيانات التجريبية.')}]);return;}setBusy(true);const version=generation.current;try{const result=await api('chat',{businessId,question,days,language:ar?'ar':'en'});if(version===generation.current)setMessages(m=>[...m,{role:'assistant',text:result.answer,toolsUsed:result.toolsUsed}]);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);} }
  function exportReport() {if(!activeReport)return;const blob=new Blob([activeReport.title+'\n\n'+activeReport.content],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='executive-report.txt';link.click();URL.revokeObjectURL(url);}
  function go(id:Page){setPage(id);setMobile(false);setSearch('');}
  const currentTitle=nav.find(n=>n.id===page)?.[ar?'ar':'en']??t('Settings','الإعدادات');
  const insight=metrics.days?(context.revenueChange===null?t('Your business at a glance.','أعمالك في لمحة.'):context.revenueChange>=0?t('A strong week. A clearer next move.','أداء متنامٍ. وخطوتك التالية أوضح.'):t('A change worth looking into.','تغير يستحق المتابعة.')):t('Your next chapter starts here.','تبدأ رحلتك من هنا.');

  return <div className="app-shell">
    {mobile&&<div className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}
    <aside className={`sidebar ${mobile?'is-open':''}`}>
      <a className="brand" href="/" aria-label="DMS Executive AI"><span className="brand-symbol"><Activity size={24}/></span><div>DMS<span>EXECUTIVE AI</span></div></a>
      <div className="workspace-picker"><span className="workspace-avatar">{business?.name[0]??'D'}</span><div><strong>{t('My workspace','مساحة أعمالي')}</strong><small>{t('Business command center','مركز قيادة الأعمال')}</small></div><ChevronDown size={14}/></div>
      <div className="nav-caption">{t('WORKSPACE','مساحة العمل')}</div>
      <nav>{nav.map((item,i)=><button key={item.id} onClick={()=>go(item.id)} className={`nav-item ${page===item.id?'active':''} ${i===7?'nav-break':''}`}><item.icon size={18}/><span>{item[ar?'ar':'en']}</span>{item.id==='executive'&&<span className="mini-ai">AI</span>}{item.id==='alerts'&&alerts.length>0&&<span className="nav-count">{alerts.length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="copilot-card"><span className="tiny-star"><Sparkles size={17}/></span><strong>{t('A little more clarity.','رؤية أكثر وضوحًا.')}</strong><p>{t('Your business data. Connected to better decisions.','بيانات أعمالك، لقرارات أفضل.')}</p><button onClick={()=>go('executive')}>{t('Meet your AI executive','تعرف على مديرك الذكي')}<ArrowUpRight size={14}/></button></div><button className={`nav-item ${page==='settings'?'active':''}`} onClick={()=>go('settings')}><Settings2 size={18}/>{t('Settings','الإعدادات')}</button><button className="profile" onClick={openWorkspace}><span className="avatar">{demo?'W':'ME'}</span><div><strong>{demo?'Waleed':t('My account','حسابي')}</strong><small>{demo?t('Demo workspace','مساحة تجريبية'):t('Personal workspace','مساحة شخصية')}</small></div><ChevronDown size={14}/></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu size={20}/></button><span className="breadcrumb-home"><BriefcaseBusiness size={15}/>{t('Workspace','مساحة العمل')}</span><span className="slash">/</span><strong>{currentTitle}</strong></div><div className="top-actions"><div className="global-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('Search workspace…','ابحث في المساحة…')} aria-label="Search workspace"/>{search&&<div className="search-results">{nav.filter(n=>(n.en+n.ar).toLowerCase().includes(search.toLowerCase())).map(n=><button key={n.id} onClick={()=>go(n.id)}>{n[ar?'ar':'en']}<ArrowRight size={14}/></button>)}</div>}</div><button className="language-button" onClick={()=>setAr(!ar)}><Globe2 size={15}/>{ar?'EN':'العربية'}</button><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button notification" onClick={()=>go('alerts')} aria-label="Notifications"><Bell size={18}/>{alerts.length>0&&<i/>}</button><span className="avatar small">W</span></div></header>
    <main>
      <div className="page-heading"><div><div className="eyebrow"><span className="status-dot"/>{t('YOUR BUSINESS, IN FOCUS','أعمالك، برؤية واضحة')}</div><h1>{page==='overview'?t('Good afternoon, Waleed','مساء الخير، وليد'):currentTitle}{page==='overview'&&<span className="greeting-dot">.</span>}</h1><p>{page==='overview'?t('Here’s the big picture. Let’s make your next move count.','إليك الصورة الكاملة. لنجعل خطوتك التالية مؤثرة.'):t('Turn business context into confident decisions.','حوّل بيانات أعمالك إلى قرارات مدروسة.')}</p></div><div className="heading-actions"><Button variant="outline" onClick={()=>setModal('data')} disabled={busy||loading||!businessId}><Plus size={15}/>{t('Add data','إضافة بيانات')}</Button><Button onClick={()=>generateReport()} disabled={busy||loading}><FileText size={15}/>{t('Generate report','إنشاء تقرير')}</Button></div></div>
      <div className="scope-bar"><div className="scope-controls"><div className="business-select"><span className="business-icon"><Building2 size={15}/></span><select aria-label="Business" value={businessId} onChange={e=>setBusinessId(e.target.value)} disabled={busy}>{businesses.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></div><span className="scope-divider"/><span className="demo-badge">{demo?t('DEMO DATA','بيانات تجريبية'):t('MANUAL DATA','بيانات يدوية')}</span><span className="data-date">{t('Through','حتى')} {p.end??'—'}</span></div><div className="period-switch">{([1,7,30] as const).map(d=><button key={d} onClick={()=>setDays(d)} className={days===d?'selected':''}>{d===1?t('Latest day','آخر يوم'):d===7?t('7 days','٧ أيام'):t('30 days','٣٠ يومًا')}</button>)}</div></div>
      {loading?<div className="empty-state"><LoaderCircle className="spin"/>{t('Loading your business…','جاري تحميل بيانات أعمالك…')}</div>:<>
      {page==='overview'&&<>
        <div className="hero-grid"><section className="brief-card"><div className="section-label"><span className="ai-icon"><Sparkles size={17}/></span>{t('EXECUTIVE BRIEF','الملخص التنفيذي')}<span className="subtle-tag">{t('Calculated insights','رؤى حسابية')}</span></div><h2>{insight}</h2><p>{metrics.days?t(`Your business generated SAR ${fmt(metrics.revenue)} across ${fmt(metrics.orders)} orders. ${context.revenueChange===null?'Add a complete previous period to compare growth.':`Revenue is ${Math.abs(context.revenueChange).toFixed(1)}% ${context.revenueChange>=0?'above':'below'} the previous period.`}`,`حققت أعمالك ${fmt(metrics.revenue)} ر.س عبر ${fmt(metrics.orders)} طلبًا. ${context.revenueChange===null?'أضف فترة سابقة كاملة لمقارنة النمو.':`تغيرت الإيرادات بنسبة ${context.revenueChange.toFixed(1)}% عن الفترة السابقة.`}`):t('Add your business metrics to uncover performance, trends and your next priorities.','أضف مؤشرات أعمالك لاكتشاف الأداء والاتجاهات وأولوياتك القادمة.')}</p><div className="brief-chips"><span><span className="status-dot"/>{t('Metrics calculated','مؤشرات محسوبة')}</span><span><ShieldCheck size={13}/>{t('No automatic actions','لا تنفيذ تلقائي')}</span></div><button className="text-link" onClick={()=>go('executive')}>{t('Explore with AI Executive','استكشف مع المدير الذكي')}<ArrowRight size={15}/></button><div className="hero-orbit"><Sparkles/></div></section>
        <section className="health-card"><div className="card-title"><h3>{t('Business health','صحة الأعمال')}</h3><CircleHelp size={15}/></div><div className="health-main"><div className="health-ring" style={{background:`conic-gradient(#25a789 ${(h?.score??0)*3.6}deg, var(--soft) 0deg)`}}><div><strong>{h?.score??'—'}</strong><span>/ 100</span></div></div><div><span className="green-label">{h?t(h.score>=80?'Doing well':h.score>=50?'Needs attention':'At risk',h.score>=80?'أداء جيد':h.score>=50?'يحتاج متابعة':'معرض للخطر'):t('No data','لا بيانات')}</span><p>{t('Finance & marketing','المالية والتسويق')}<br/>{t('Partial health score','تقييم جزئي للصحة')}</p></div></div><div className="health-footer"><span>{t('Based on entered costs and revenue','وفق التكاليف والإيرادات المدخلة')}</span><button onClick={()=>go('analytics')} aria-label="Health details"><ArrowUpRight size={16}/></button></div></section></div>
        <div className="kpi-grid">{[
          {label:t('Total revenue','إجمالي الإيرادات'),value:fmt(metrics.revenue),unit:'SAR',icon:Wallet,note:t('Across the selected period','خلال الفترة المحددة'),trend:context.revenueChange},
          {label:t('Orders','الطلبات'),value:fmt(metrics.orders),unit:'',icon:BriefcaseBusiness,note:t(`SAR ${fmt(metrics.aov,2)} average order value`,`${fmt(metrics.aov,2)} ر.س متوسط الطلب`),trend:null},
          {label:t('Ad spend','الإنفاق الإعلاني'),value:fmt(metrics.adSpend),unit:'SAR',icon:Target,note:t('Total entered advertising costs','إجمالي تكاليف الإعلانات المدخلة'),trend:null},
          {label:t('Estimated net profit','صافي الربح التقديري'),value:fmt(metrics.profit),unit:'SAR',icon:ChartNoAxesCombined,note:t(`${fmt(metrics.margin,1)}% net margin · entered costs`,`${fmt(metrics.margin,1)}% هامش الربح · التكاليف المدخلة`),trend:null},
        ].map((k,i)=><section className="kpi-card" key={k.label}><div className="kpi-top"><span>{k.label}</span><k.icon size={17}/></div><div className="kpi-value"><span>{k.unit}</span>{k.value}</div><div className="kpi-bottom">{k.trend!==null?<><span className={k.trend>=0?'positive':'negative'}>{k.trend>=0?<ArrowUpRight size={13}/>:<ArrowDownLeft size={13}/>} {Math.abs(k.trend).toFixed(1)}%</span><span>{t('vs. previous period','مقابل الفترة السابقة')}</span></>:<span>{k.note}</span>}<svg viewBox="0 0 75 25" aria-hidden="true"><polyline points={p.current.slice(-12).map((r,j)=>`${j/Math.max(Math.min(p.current.length,12)-1,1)*75},${24-(i===2?r.adSpend:r.revenue)/Math.max(...p.current.map(v=>i===2?v.adSpend:v.revenue),1)*21}`).join(' ')} fill="none" stroke={i===2?'#8795ac':'#31a48b'} strokeWidth="1.5"/></svg></div></section>)}</div>
        <div className="content-grid"><section className="panel performance-panel"><div className="panel-heading"><div><h3>{t('Revenue performance','أداء الإيرادات')}</h3><p>{t('A clearer view of your business momentum','صورة أوضح لاتجاه أعمالك')}</p></div><span className="subtle-tag">SAR</span></div><div className="chart-legend"><span><i className="blue-dot"/>{t('Revenue','الإيرادات')}</span><span><i className="teal-dot"/>{t('Ad spend','الإنفاق الإعلاني')}</span><small>{t(`${p.current.length} of ${days} days available`,`${p.current.length} من ${days} أيام متاحة`)}</small></div><TrendChart rows={p.current} ar={ar}/><div className="chart-insight"><Sparkles size={15}/><span>{t(`Blended return is ${fmt(metrics.roas,2)}x. Connect channel data to understand what drives it.`,`العائد المدمج ${fmt(metrics.roas,2)}. اربط بيانات القنوات لفهم أسباب الأداء.`)}</span></div></section>
        <section className="panel priorities-panel"><div className="panel-heading"><div><h3>{t('Your next moves','خطواتك القادمة')}</h3><p>{t('A little focus goes a long way','أولويات واضحة لنتائج أفضل')}</p></div><span className="count-pill">3</span></div>{[
          {n:'01',title:t('Bring your data together','اجمع بيانات أعمالك'),body:t('Start with your store and ad platforms.','ابدأ بمتجرك ومنصات الإعلانات.'),tag:t('FOUNDATION','الأساس'),color:'blue',action:()=>go('integrations')},
          {n:'02',title:t('Check the full cost picture','راجع جميع التكاليف'),body:t('Include product and operating costs.','أدرج تكاليف المنتجات والتشغيل.'),tag:t('FINANCE','المالية'),color:'orange',action:()=>setModal('data')},
          {n:'03',title:t('Make time for a business review','راجع أداء أعمالك'),body:t('Turn this period’s results into a plan.','حوّل نتائج الفترة إلى خطة عمل.'),tag:t('PLANNING','التخطيط'),color:'purple',action:()=>generateReport()},
        ].map(item=><button className="priority-row" key={item.n} onClick={item.action}><span className="priority-number">{item.n}</span><div><span className={`priority-tag ${item.color}`}>{item.tag}</span><strong>{item.title}</strong><p>{item.body}</p></div><ArrowUpRight size={15}/></button>)}</section></div>
<div className="bottom-grid"><section className="panel"><div className="panel-heading"><div><h3>{t('Your data sources','مصادر بياناتك')}</h3><p>{t('Build a connected business picture','كوّن صورة مترابطة لأعمالك')}</p></div><button className="text-link" onClick={()=>go('integrations')}>{t('View all','عرض الكل')}<ArrowRight size={14}/></button></div><div className="source-row">{integrationCatalog.slice(0,4).map(c=><button key={c.id} onClick={()=>{setProvider(c.name);setModal('integration');}}><span className="provider-logo" style={{color:c.color,background:c.color+'12'}}>{c.letter}</span><strong>{c.name}</strong><small>{demo?t('Not connected','غير متصل'):t('View connection status','عرض حالة الاتصال')}</small></button>)}</div></section><section className="ask-card"><span className="ai-icon"><Sparkles size={19}/></span><div><h3>{t('Less digging. More direction.','وقت أقل للبحث. رؤية أوضح.')}</h3><p>{t('Ask your AI executive about the numbers.','اسأل مديرك الذكي عن أداء أعمالك.')}</p></div><button onClick={()=>go('executive')} aria-label="Open AI chat"><ArrowRight size={19}/></button></section></div>
      </>}

      {page==='integrations'&&<IntegrationHub key={businessId+(demo?'demo':'live')} businessId={businessId} demo={demo} ar={ar} token={token} onSignIn={openWorkspace} pendingSelection={pendingSelection} onPendingSelectionHandled={()=>setPendingSelection(null)}/>}
      {['automation','tasks','alerts'].includes(page)&&<OperationsHub key={`${businessId}:${demo}:${page}:${token}`} businessId={businessId} demo={demo} ar={ar} token={token} rows={rows} initialTab={page==='tasks'?'tasks':page==='alerts'?'alerts':'rules'}/>}
      {['overview','marketing','analytics','sales'].includes(page)&&<SourceInsights summaries={sourceData} ar={ar}/>}
      {page==='executive'&&<section className="panel brief-card"><div className="section-label"><span className="ai-icon"><Sparkles size={17}/></span>{t('EXECUTIVE BRIEF','الملخص التنفيذي')}<span className="subtle-tag">{t('AI-generated','مولّد بالذكاء الاصطناعي')}</span></div>{demo?<p>{t('Executive Brief requires a signed-in workspace with a configured AI provider and synchronized data.','يتطلب الملخص التنفيذي مساحة عمل مسجلة ومزود ذكاء اصطناعي مهيأ وبيانات متزامنة.')}</p>:briefLoading?<div className="empty-state"><LoaderCircle className="spin"/>{t('Generating your executive brief…','جارٍ إنشاء ملخصك التنفيذي…')}</div>:briefError?<div className="inline-note"><CircleHelp size={18}/>{briefError}</div>:brief?<>
        <p>{brief.summary}</p>
        <div className="detail-metrics">
          <section className="panel detail-kpi"><p>{t('Top win','أهم إنجاز')}</p><h2>{brief.wins[0]??t('None identified','لا يوجد')}</h2></section>
          <section className="panel detail-kpi"><p>{t('Top problem','أهم مشكلة')}</p><h2>{brief.problems[0]??t('None identified','لا يوجد')}</h2></section>
          <section className="panel detail-kpi"><p>{t('Top opportunity','أهم فرصة')}</p><h2>{brief.opportunities[0]??t('None identified','لا يوجد')}</h2></section>
          <section className="panel detail-kpi"><p>{t('Recommended action','قرار مقترح')}</p><h2>{brief.recommendedActions[0]??t('None yet','لا يوجد بعد')}</h2></section>
        </div>
        <div className="brief-chips"><span><ShieldCheck size={13}/>{t('Confidence','الثقة')} {Math.round(brief.confidence*100)}%</span><span>{brief.dataFreshness}</span></div>
      </>:<p>{t('No data available yet. Connect and synchronize a data source to generate a brief.','لا توجد بيانات متاحة بعد. اربط مصدر بيانات وزامنه لإنشاء ملخص.')}</p>}</section>}
      {page==='executive'&&<section className="panel chat-panel"><div className="panel-heading"><div className="chat-title"><span className="ai-icon"><Sparkles size={20}/></span><div><h3>{t('Your AI chief of staff','مدير مكتبك الذكي')}</h3><p>{t('Grounded in your business. Focused on your next move.','يستند إلى بيانات أعمالك ويركز على خطوتك التالية.')}</p></div></div><span className="subtle-tag">{demo?t('Demo preview','معاينة تجريبية'):t('Executive agent','الوكيل التنفيذي')}</span></div><div className="chat-messages">{!messages.length?<div className="chat-welcome"><div className="large-ai"><Sparkles size={30}/></div><h2>{t('What’s on your mind?','ما الذي يشغل بالك؟')}</h2><p>{t('Explore performance, uncover risks, and plan what comes next.','استكشف الأداء والمخاطر وخطط للخطوة القادمة.')}</p><div className="suggestions">{[t('How is my business doing?','كيف حال أعمالي؟'),t('Are we profitable this week?','هل نحقق أرباحًا هذا الأسبوع؟'),t('Are any products low on stock?','هل توجد منتجات مخزونها منخفض؟'),t('How many customers do we have?','كام عدد عملائنا؟'),t('When was our data last synced?','آخر مزامنة كانت إمتى؟'),t('What should I focus on next?','ما الذي ينبغي التركيز عليه؟')].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={14}/></button>)}</div><div className="capabilities-note"><ShieldCheck size={13}/>{t('Every answer is backed by a real tool call — revenue, orders, inventory, customers and data freshness — never a guess.','كل إجابة مبنية على استدعاء أداة حقيقية — إيرادات، طلبات، مخزون، عملاء، وحداثة البيانات — مش تخمين.')}</div></div>:messages.map((m,i)=><div key={i} className={`chat-message ${m.role}`}><span className="message-avatar">{m.role==='user'?'W':<Sparkles size={16}/>}</span><div><small>{m.role==='user'?t('You','أنت'):t('AI Executive','المدير الذكي')}</small><p dir="auto">{m.text}</p>{!!m.toolsUsed?.length&&<div className="tool-chips">{m.toolsUsed.map(name=><span key={name} className="tool-chip"><Sparkles size={11}/>{ar?(TOOL_LABELS[name]?.ar??name):(TOOL_LABELS[name]?.en??name)}</span>)}</div>}</div></div>)}{busy&&<div className="thinking"><LoaderCircle className="spin" size={16}/>{t('Reviewing your business context…','جاري مراجعة بيانات أعمالك…')}</div>}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();ask();}}><input value={query} onChange={e=>setQuery(e.target.value)} maxLength={2000} placeholder={t('Ask about your business…','اسأل عن أعمالك…')} aria-label="Your question"/><Button disabled={busy||!query.trim()} type="submit" aria-label="Send question"><Send size={17}/></Button></form><p className="chat-footnote">{t('AI is advisory. Verify recommendations before making decisions.','الذكاء الاصطناعي استشاري. تحقق من التوصيات قبل اتخاذ القرارات.')}</p></section>}
      {['sales','finance','marketing','analytics'].includes(page)&&<><div className="detail-metrics">{[{label:t('Revenue','الإيرادات'),value:`SAR ${fmt(metrics.revenue)}`},{label:t('Entered total costs','إجمالي التكاليف المدخلة'),value:`SAR ${fmt(metrics.cogs+metrics.adSpend+metrics.expenses)}`},{label:t('Blended ROAS','العائد المدمج'),value:`${fmt(metrics.roas,2)}x`},{label:t('Conversion rate','معدل التحويل'),value:`${fmt(metrics.conversion,2)}%`}].map(v=><section className="panel detail-kpi" key={v.label}><p>{v.label}</p><h2>{v.value}</h2></section>)}</div><section className="panel"><div className="panel-heading"><div><h3>{t('Performance over time','الأداء بمرور الوقت')}</h3><p>{t('Revenue and advertising spend · SAR','الإيرادات والإنفاق الإعلاني · ر.س')}</p></div></div><TrendChart rows={p.current} ar={ar}/></section><section className="panel records-panel"><div className="panel-heading"><div><h3>{t('Daily records','السجلات اليومية')}</h3><p>{t('Profit = revenue − product costs − ad spend − operating expenses','الربح = الإيرادات − تكلفة المنتجات − الإعلانات − مصروفات التشغيل')}</p></div><Button variant="outline" onClick={()=>setModal('data')}><Plus size={14}/>{t('Add / replace day','إضافة / استبدال يوم')}</Button></div><div className="table-scroll"><table><thead><tr>{[t('Date','التاريخ'),t('Revenue','الإيرادات'),t('Orders','الطلبات'),t('Ad spend','الإعلانات'),t('COGS','تكلفة المنتجات'),t('Expenses','المصروفات'),t('Profit','الربح')].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{p.current.map(r=><tr key={r.date}><td>{r.date}</td><td>{fmt(r.revenue)}</td><td>{fmt(r.orders)}</td><td>{fmt(r.adSpend)}</td><td>{fmt(r.cogs)}</td><td>{fmt(r.expenses)}</td><td className={r.revenue-r.cogs-r.adSpend-r.expenses>=0?'positive':'negative'}>{fmt(r.revenue-r.cogs-r.adSpend-r.expenses)}</td></tr>)}</tbody></table></div></section>{page==='marketing'&&<div className="inline-note"><CircleHelp size={18}/>{t('These are blended metrics. Channel attribution, campaign comparisons and budget recommendations require connected ad platforms.','هذه مؤشرات مدمجة. تتطلب مقارنة الحملات وتوصيات الميزانية ربط منصات الإعلانات.')}</div>}{page==='analytics'&&<div className="inline-note"><CircleHelp size={18}/>{t('Health uses profitability (60%) and blended ROAS (40%). Targets: 40% margin, 5x ROAS. Customer, project and IT health are not measured yet.','الصحة تعتمد على الربحية (٦٠٪) والعائد المدمج (٤٠٪). الأهداف: هامش ٤٠٪ وعائد ٥. لا يشمل التقييم العملاء والمشاريع وتقنية المعلومات حاليًا.')}</div>}</>}
      {page==='businesses'&&<div className="integration-grid">{businesses.map(b=><section className="panel business-card" key={b.id}><span className="workspace-avatar">{b.name[0]}</span><h2>{b.name}</h2><p>{t('Saudi Riyal · Asia/Riyadh','ريال سعودي · الرياض')}</p><span className="subtle-tag">{demo?t('Demo business','عمل تجريبي'):t('Your business','أعمالك')}</span><Button variant="outline" onClick={()=>{setBusinessId(b.id);go('overview');}}>{t('Open dashboard','فتح لوحة التحكم')}<ArrowRight size={15}/></Button></section>)}<button className="new-business" onClick={()=>setModal('business')}><Plus size={27}/><strong>{t('Add a business','إضافة عمل')}</strong><span>{t('Give every business its own space','مساحة مستقلة لكل عمل')}</span></button></div>}
      {page==='reports'&&<section className="panel"><div className="panel-heading"><div><h3>{t('Executive reports','التقارير التنفيذية')}</h3><p>{t('Saved snapshots of your business performance.','لقطات محفوظة لأداء أعمالك.')}</p></div><Button onClick={()=>generateReport(true)} disabled={busy}><Sparkles size={16}/>{t('Generate with AI','إنشاء بالذكاء الاصطناعي')}</Button></div>{reports.length?reports.map(r=><button className="report-row" onClick={()=>{setActiveReport(r);setModal('report');}} key={r.id}><span className="report-icon"><FileText size={22}/></span><div><strong>{r.title}</strong><p>{demo?t('Saved in this browser · Demo data','محفوظ في المتصفح · بيانات تجريبية'):t('Saved to your workspace','محفوظ في مساحة أعمالك')}</p></div><ArrowUpRight size={18}/></button>):<div className="empty-state"><FileText size={34}/><h3>{t('Your first review starts here','ابدأ مراجعتك الأولى')}</h3><p>{t('Generate a report from your selected business and date range.','أنشئ تقريرًا للعمل والفترة المحددين.')}</p><Button onClick={()=>generateReport()}>{t('Generate report','إنشاء تقرير')}</Button></div>}</section>}
      {page==='alerts'&&<section className="panel"><div className="panel-heading"><div><h3>{t('Needs your attention','يحتاج انتباهك')}</h3><p>{t('Rule-based checks on the selected period.','فحوص حسابية للفترة المحددة.')}</p></div><span className="count-pill">{alerts.length}</span></div>{alerts.length?alerts.map((a,i)=><div className="alert-row" key={i}><TriangleAlert size={21}/><div><strong>{a}</strong><p>{t('Source: entered daily metrics. Review data before acting.','المصدر: المؤشرات اليومية المدخلة. راجع البيانات قبل اتخاذ إجراء.')}</p></div><Button variant="outline" onClick={()=>setModal('data')}>{t('Review data','مراجعة البيانات')}</Button></div>):<div className="empty-state"><ShieldCheck size={36}/><h3>{t('No threshold alerts in this period','لا توجد تنبيهات للحدود في هذه الفترة')}</h3><p>{t('This does not assess website uptime, inventory or customer support.','لا يشمل ذلك توفر الموقع أو المخزون أو دعم العملاء.')}</p></div>}</section>}
      {page==='settings'&&<section className="panel settings-panel"><h3>{t('Make this space yours','اجعل هذه المساحة لك')}</h3><div className="setting-row"><div><strong>{t('Language','اللغة')}</strong><p>{t('English or Arabic with full RTL layout','الإنجليزية أو العربية مع اتجاه من اليمين لليسار')}</p></div><Button variant="outline" onClick={()=>setAr(!ar)}>{ar?'English':'العربية'}</Button></div><div className="setting-row"><div><strong>{t('Appearance','المظهر')}</strong><p>{t('Choose light or dark mode','اختر الوضع الفاتح أو الداكن')}</p></div><Button variant="outline" onClick={()=>setDark(!dark)}>{dark?<Sun size={16}/>:<Moon size={16}/>} {dark?t('Light','فاتح'):t('Dark','داكن')}</Button></div><div className="setting-row"><div><strong>{t('Your account','حسابك')}</strong><p>{demo?t('Explore demo data or sign in to your workspace.','استكشف البيانات التجريبية أو سجل الدخول لمساحتك.'):t('Your data is saved to your organization.','تُحفظ البيانات داخل مؤسستك.')}</p></div><Button onClick={openWorkspace}>{token?t('Open my workspace','فتح مساحتي'):t('Sign in','تسجيل الدخول')}</Button></div>{token&&<div className="setting-row"><div><strong>{t('End session','إنهاء الجلسة')}</strong></div><Button variant="outline" onClick={async()=>{await supabase?.auth.signOut();setDemo(true);setBusinesses(demoBusinesses);setBusinessId('demo-natural');}}><LogOut size={16}/>{t('Sign out','تسجيل الخروج')}</Button></div>}<div className="inline-note"><ShieldCheck size={20}/>{t('No external action is executed in this MVP. AI credentials stay on the server.','لا تُنفذ إجراءات خارجية في هذا الإصدار. تبقى مفاتيح AI على الخادم.')}</div></section>}
      </>}
      <footer className="page-footer"><span><span className="status-dot"/>{demo?t('Demo mode · Sample business data','الوضع التجريبي · بيانات أعمال نموذجية'):t('Workspace · Manual data source','مساحة العمل · بيانات يدوية')}</span><span>DMS Executive AI <span className="footer-dot">·</span> {t('Built for the bigger picture','رؤية تتجاوز الأرقام')}</span></footer>
    </main></div>
    {notice&&<div className="toast" role="status"><CircleHelp size={18}/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={16}/></button></div>}
    {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal(null);}}><section className={`modal ${modal==='report'?'report-modal':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close icon-button" onClick={()=>setModal(null)} aria-label="Close"><X size={20}/></button>
      {modal==='data'&&<><span className="modal-icon"><Database size={23}/></span><h2 id="modal-title">{t('Add daily business data','إضافة بيانات يومية')}</h2><p>{t('One complete record per day. Saving an existing date replaces that day’s values. All amounts in SAR.','سجل كامل لكل يوم. حفظ تاريخ موجود يستبدل قيم ذلك اليوم. المبالغ بالريال السعودي.')}</p><form onSubmit={saveData} className="data-form"><label className="full-width">{t('Date','التاريخ')}<input type="date" name="date" required defaultValue={p.end??new Date().toISOString().slice(0,10)}/></label>{[['revenue',t('Revenue','الإيرادات')],['orders',t('Orders','الطلبات')],['adSpend',t('Ad spend','الإنفاق الإعلاني')],['cogs',t('Product costs','تكلفة المنتجات')],['expenses',t('Operating expenses','مصروفات التشغيل')],['leads',t('New leads','عملاء محتملون')],['sessions',t('Sessions','الجلسات')]].map(([name,label])=><label key={name}>{label}<input name={name} type="number" min="0" max={['orders','leads'].includes(name)?10000000:name==='sessions'?100000000:1000000000} step={['orders','leads','sessions'].includes(name)?'1':'0.01'} required placeholder="0"/></label>)}<Button className="full-width" disabled={busy} type="submit">{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {t('Save and recalculate','حفظ وإعادة الحساب')}</Button></form></>}
      {modal==='business'&&<><h2 id="modal-title">{t('Create a business workspace','إنشاء مساحة أعمال')}</h2><p>{t('Keep your business data and reports in one dedicated space.','احفظ بيانات وتقارير أعمالك في مساحة مستقلة.')}</p><form onSubmit={saveBusiness} className="simple-form"><label>{t('Business name','اسم العمل')}<input name="name" required minLength={2} maxLength={80} placeholder="My business"/></label><Button disabled={busy} type="submit">{t('Create workspace','إنشاء المساحة')}</Button></form></>}
      {modal==='login'&&<><span className="modal-icon"><ShieldCheck size={24}/></span><h2 id="modal-title">{t('Your business. Your workspace.','أعمالك. مساحتك الخاصة.')}</h2><p>{t('Sign in to save real business data.','سجل الدخول لحفظ بيانات أعمالك الفعلية.')}</p><Button variant="outline" className="full-width" disabled={busy} onClick={loginWithGoogle}><GoogleIcon/>{t('Continue with Google','المتابعة بحساب Google')}</Button><div className="auth-divider"><span/>{t('or','أو')}<span/></div><form onSubmit={login} className="simple-form"><label>{t('Email address','البريد الإلكتروني')}<input type="email" name="email" required placeholder="you@company.com"/></label><Button disabled={busy} type="submit">{t('Email me a sign-in link','إرسال رابط الدخول')}</Button></form></>}
      {modal==='integration'&&<><span className="modal-icon"><Plug size={24}/></span><h2 id="modal-title">{provider}</h2><p>{t('Manage secure connections and read-only synchronization from the integration hub. No credentials are collected in demo mode.','أدر الاتصالات الآمنة والمزامنة للقراءة من مركز التكاملات. لا تُجمع بيانات اعتماد في الوضع التجريبي.')}</p><Button onClick={()=>{setModal(null);go('integrations');}}><Plug size={16}/>{t('Open integration hub','فتح مركز التكاملات')}</Button></>}
      {modal==='report'&&activeReport&&<><h2 id="modal-title">{activeReport.title}</h2><span className="subtle-tag">{demo?t('Demo data · Calculated report','بيانات تجريبية · تقرير حسابي'):t('Workspace report','تقرير مساحة العمل')}</span><pre dir="auto" className="report-content">{activeReport.content}</pre><div className="report-actions"><Button variant="outline" onClick={exportReport}><Download size={16}/>{t('Download text','تنزيل النص')}</Button><Button onClick={()=>window.print()}><FileText size={16}/>{t('Print / Save PDF','طباعة / حفظ PDF')}</Button></div></>}
    </section></div>}
  </div>;
}
