'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { ArrowUpRight,Check,Clock3,KeyRound,LoaderCircle,Plug,RefreshCw,ShieldCheck,Unplug,X } from 'lucide-react';
import { Button } from './ui/button';
import { integrationCatalog } from '@/modules/integrations/contracts';
import { providerSchema,type ProviderId,type SourceSummary } from '@/modules/integrations/types';
type Connection={provider:string;status:string;accountId:string|null;lastSync:string|null;lastError:string|null;autoSync:boolean;syncRuns:{id:string;status:string;records:number;errorCode:string|null;createdAt:string;from:string;to:string}[]};
type HubData={integrations:Connection[];summaries:SourceSummary[];canManage:boolean;oauth:Partial<Record<ProviderId,boolean>>;workerConfigured:boolean};
const empty:HubData={integrations:[],summaries:[],canManage:false,oauth:{},workerConfigured:false};
export function IntegrationHub({businessId,demo,ar,token,onSignIn,pendingSelection,onPendingSelectionHandled}:{businessId:string;demo:boolean;ar:boolean;token:string;onSignIn:()=>void;pendingSelection?:{provider:string;state:string}|null;onPendingSelectionHandled?:()=>void}){
  const [data,setData]=useState<HubData>(empty),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('All'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmDisconnect,setConfirmDisconnect]=useState(false);
  const [from,setFrom]=useState(()=>new Date(Date.now()-29*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
  const [accountChoices,setAccountChoices]=useState<{id:string;name:string}[]|null>(null),[chosenAccount,setChosenAccount]=useState('');
  const alive=useRef(true),detail=useRef<HTMLElement>(null),t=(en:string,arabic:string)=>ar?arabic:en;
  async function request(path:string,payload?:unknown){const response=await fetch('/api/'+path,{method:payload?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error??'Request failed');return result;}
  async function reload(){if(demo)return;try{const result=await request(`integrations?businessId=${encodeURIComponent(businessId)}`);if(alive.current)setData(result);}catch(e){if(alive.current)setError((e as Error).message);}}
  useEffect(()=>{alive.current=true;void reload();const timer=setInterval(()=>{if(document.visibilityState==='visible')void reload();},5000);return()=>{alive.current=false;clearInterval(timer);};},[businessId,demo,token]);
  useEffect(()=>{if(selected)detail.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});},[selected]);
  useEffect(()=>{if(!pendingSelection?.provider||!pendingSelection.state||demo)return;setSelected(pendingSelection.provider);setError('');request(`integrations/oauth/pending?state=${encodeURIComponent(pendingSelection.state)}`).then(result=>setAccountChoices(result.accounts)).catch(e=>{setError((e as Error).message);onPendingSelectionHandled?.();});},[pendingSelection,demo]);
  async function action(action:string,extra:object={}){if(demo)return;setBusy(true);setError('');try{await request('integrations',{action,businessId,provider:selected,...extra});setNotice(t(action==='sync'?'Sync queued. Results appear when the worker finishes.':'Connection updated.','sync'===action?'أُضيفت المزامنة إلى الطابور. تظهر النتائج بعد اكتمال العامل.':'تم تحديث الاتصال.'));setConfirmDisconnect(false);await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function connect(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,values=new FormData(form);const credentials=Object.fromEntries([...values.entries()].filter(([,v])=>v!==''));if(credentials.expiresAt)credentials.expiresAt=new Date(String(credentials.expiresAt)).toISOString();await action('connect',{credentials});form.reset();}
  async function oauth(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const result=await request('integrations/oauth',{businessId,provider:selected});window.location.assign(result.url);}catch(e){setError((e as Error).message);setBusy(false);}}
  async function confirmAccount(){if(!pendingSelection||!chosenAccount)return;setBusy(true);setError('');try{await request('integrations/oauth/select-account',{state:pendingSelection.state,accountId:chosenAccount});setAccountChoices(null);setChosenAccount('');onPendingSelectionHandled?.();setNotice(t('Account connected.','تم ربط الحساب.'));await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const provider=integrationCatalog.find(p=>p.id===selected),connection=data.integrations.find(c=>c.provider===selected),supported=providerSchema.safeParse(selected).success;
  const showingAccountPicker=!!accountChoices&&selected===pendingSelection?.provider;
  const status=(value:string)=>({connected:t('Connected','متصل'),disconnected:t('Not connected','غير متصل'),needs_reconnection:t('Reconnect needed','يلزم إعادة الربط'),queued:t('Queued','في الانتظار'),running:t('Running','قيد التنفيذ'),completed:t('Completed','مكتمل'),failed:t('Failed','فشل'),cancelled:t('Cancelled','ملغى')}[value]??value);
  return <div className="integration-hub"><div className="section-intro"><div><h2>{t('Your business, connected.','أعمالك، مترابطة.')}</h2><p>{t('Six read-only connectors. Secure credentials, scheduled sync, and a clear history of every import.','ستة موصلات للقراءة. اعتماد مشفر ومزامنة مجدولة وسجل واضح لكل استيراد.')}</p></div><span className="green-label">{data.integrations.filter(c=>c.status==='connected').length} {t('connected','متصل')}</span></div>
    {demo&&<div className="inline-note"><ShieldCheck size={19}/><div>{t('You are in demo mode. Connections require a signed-in business. No credentials are collected in the demo.','أنت في الوضع التجريبي. الربط يتطلب مساحة أعمال مسجلة. لا تُجمع بيانات اعتماد في الوضع التجريبي.')} <button className="text-link" onClick={onSignIn}>{t('Open my workspace','فتح مساحة أعمالي')}</button></div></div>}
    {error&&<div className="hub-message error" role="alert">{error}</div>}{notice&&<div className="hub-message" role="status">{notice}<button className="icon-button" onClick={()=>setNotice('')} aria-label="Dismiss"><X size={14}/></button></div>}
    <div className="filter-tabs">{['All','Commerce','Advertising','Analytics','Communication'].map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{ar?({All:'الكل',Commerce:'التجارة',Advertising:'الإعلانات',Analytics:'التحليلات',Communication:'التواصل'}[f]):f}</button>)}</div>
    <div className="integration-grid">{integrationCatalog.filter(c=>filter==='All'||c.category===filter).map(c=>{const state=data.integrations.find(i=>i.provider===c.id),available=providerSchema.safeParse(c.id).success;return <section className={`panel integration-card ${selected===c.id?'selected-provider':''}`} key={c.id}><div className="integration-top"><span className="provider-logo" style={{color:c.color,background:c.color+'14'}}>{c.letter}</span><span className={state?.status==='connected'?'green-label':'subtle-tag'}>{available?status(state?.status??'disconnected'):t('Planned','مخطط')}</span></div><h3>{c.name}</h3><p>{c.category} · {t('Read only','قراءة فقط')}</p><div className="integration-bottom"><small>{state?.lastSync?new Date(state.lastSync).toLocaleString(ar?'ar-SA':'en-GB'):t('Last sync: never','آخر مزامنة: لا توجد')}</small><Button variant="outline" onClick={()=>{setSelected(c.id);setConfirmDisconnect(false);setNotice('');}}>{state?.status==='connected'?t('Manage','إدارة'):t('Connect account','ربط الحساب')}<ArrowUpRight size={14}/></Button></div>{state?.lastError&&<p className="negative">{state.lastError}</p>}</section>;})}</div>
    {provider&&<section ref={detail} className="panel connection-detail" aria-label={t('Connection setup','إعداد الاتصال')}><div className="panel-heading"><div><h3>{provider.name}</h3><p>{t('Credentials are encrypted on the server and are never returned to this screen.','تُشفّر بيانات الاعتماد على الخادم ولا تُعاد إلى هذه الشاشة.')}</p></div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Close setup"><X size={19}/></button></div>
      {!supported?<div className="empty-state"><Plug size={30}/><p>{t('This provider is planned for a later connector release.','هذا المزود مخطط لإصدار لاحق من الموصلات.')}</p></div>:demo?<div className="empty-state"><ShieldCheck size={30}/><p>{t('No credentials are collected in demo mode. Sign in to connect your own account.','لا تُجمع بيانات اعتماد في الوضع التجريبي. سجل الدخول لربط حسابك.')}</p><Button onClick={onSignIn}>{t('Sign in','تسجيل الدخول')}</Button></div>:!data.canManage?<div className="empty-state">{t('Only workspace owners and admins can manage connections.','يمكن لمالك المساحة والمديرين فقط إدارة الاتصالات.')}</div>:<div className="connection-body">
        {connection?.status==='connected'&&<div className="sync-controls"><div className="sync-heading"><span className="green-label"><Check size={13}/> {t('Verified connection','اتصال متحقق')}</span><label className="toggle-label"><input type="checkbox" checked={connection.autoSync} disabled={busy} onChange={e=>action('schedule',{enabled:e.target.checked})}/>{t('Sync hourly (last 30 days)','مزامنة كل ساعة (آخر ٣٠ يومًا)')}</label></div><div className="sync-range"><label>{t('From','من')}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{t('To','إلى')}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><Button disabled={busy} onClick={()=>action('sync',{range:{from,to}})}><RefreshCw size={15}/>{t('Sync now','مزامنة الآن')}</Button></div><p className="setup-hint">{t('Up to 31 days per request. Existing imported dates are replaced atomically. Manual records stay separate.','حتى ٣١ يومًا لكل طلب. تُستبدل الأيام المستوردة ذريًا. تبقى السجلات اليدوية منفصلة.')}</p>{!data.workerConfigured&&<p className="negative">{t('The sync worker needs Redis configuration.','عامل المزامنة يحتاج إعداد Redis.')}</p>}</div>}
        {showingAccountPicker&&<div className="oauth-form"><h4>{t('Choose an account','اختر حسابًا')}</h4><p className="setup-hint">{t('This authorization can reach more than one account. Pick the one to connect to this business.','يمكن لهذا التفويض الوصول لأكثر من حساب. اختر الحساب المطلوب ربطه بهذا العمل.')}</p><div className="account-choices">{accountChoices.map(a=><label key={a.id}><input type="radio" name="accountChoice" value={a.id} checked={chosenAccount===a.id} onChange={()=>setChosenAccount(a.id)}/>{a.name}</label>)}</div><Button disabled={busy||!chosenAccount} onClick={confirmAccount}><ShieldCheck size={15}/>{t('Connect selected account','ربط الحساب المحدد')}</Button></div>}
        {!showingAccountPicker&&data.oauth[selected as ProviderId]&&<form className="oauth-form" onSubmit={oauth}><h4>{t('Connect with OAuth','الربط عبر OAuth')}</h4>
          <ul className="consent-summary">{(provider?.category==='Commerce'?[t('Store information','معلومات المتجر'),t('Orders','الطلبات'),t('Products','المنتجات'),t('Customers','العملاء'),t('Inventory status','حالة المخزون')]:[t('Account information','معلومات الحساب'),t('Read-only performance data (spend, clicks, sessions, conversions as applicable)','بيانات أداء للقراءة فقط (الإنفاق، النقرات، الجلسات، التحويلات حسب المتاح)')]).map(item=><li key={item}><Check size={13}/>{item}</li>)}</ul>
          <p className="setup-hint">{t('DMS Executive AI will not edit products, change prices, or cancel orders. You approve the exact permissions on the next screen, hosted by the provider.','لن يقوم DMS Executive AI بتعديل المنتجات أو تغيير الأسعار أو إلغاء الطلبات. ستوافق على الصلاحيات الدقيقة في الشاشة التالية التابعة للمزود.')}</p>
          {selected==='salla'&&<p className="setup-hint">{t('Salla Custom OAuth is for development/testing. Public Salla apps require Easy Mode onboarding.','OAuth المخصص لسلة للتطوير والاختبار. تطبيقات متجر سلة العامة تتطلب Easy Mode.')}</p>}
          <Button disabled={busy} type="submit"><ShieldCheck size={15}/>{t('Continue to provider','المتابعة إلى المزود')}</Button></form>}
        {!showingAccountPicker&&!data.oauth[selected as ProviderId]&&<details className="token-details" open={connection?.status!=='connected'}><summary><KeyRound size={15}/>{t('Connect / replace an existing access token','ربط / استبدال رمز وصول موجود')}</summary><p className="setup-hint">{t('This provider does not yet have an OAuth login here. Use an access token issued by your provider with read permissions; it is sent once and saved encrypted.','لا يتوفر تسجيل دخول OAuth لهذا المزود بعد. استخدم رمز وصول صادرًا من المزود بصلاحيات القراءة؛ يُرسل مرة واحدة ويُحفظ مشفرًا.')}</p><form className="data-form" onSubmit={connect} autoComplete="off"><label className="full-width">{selected==='zid'?'X-Manager-Token':'Access token'}<input type="password" name="accessToken" required minLength={10} maxLength={8192} autoComplete="new-password"/></label>{selected==='zid'&&<label className="full-width">Authorization token<input type="password" name="authorizationToken" required maxLength={8192} autoComplete="new-password"/></label>}{!['salla','zid'].includes(selected!)&&<label>{selected==='ga4'?t('Property ID','معرف الموقع'):t('Account ID (digits only)','معرف الحساب (أرقام فقط)')}<input name="accountId" required pattern="[0-9]{1,30}" defaultValue={connection?.accountId??''}/></label>}{selected==='google-ads'&&<><label>Developer token<input name="developerToken" type="password" required autoComplete="new-password"/></label><label>Login customer ID<input name="loginCustomerId" pattern="[0-9]{1,30}"/></label></>}<label>{t('Token expiry (if known)','انتهاء الرمز (إن عُرف)')}<input type="datetime-local" name="expiresAt"/></label>{['salla','zid','ga4','google-ads'].includes(selected!)&&<label className="full-width">{t('Refresh token (optional)','رمز التجديد (اختياري)')}<input type="password" name="refreshToken" maxLength={8192} autoComplete="new-password"/></label>}<Button disabled={busy} type="submit" className="full-width">{busy?<LoaderCircle className="spin" size={15}/>:<ShieldCheck size={15}/>} {t('Verify and connect','التحقق والربط')}</Button></form></details>}
        {connection&&connection.status!=='disconnected'&&<div className="disconnect-box">{confirmDisconnect?<><p>{t('Disconnect this account? Local tokens will be deleted and future imports stopped. Revoke app access at the provider separately.','فصل هذا الحساب؟ ستُحذف الرموز المحلية وتتوقف الاستيرادات القادمة. ألغِ وصول التطبيق لدى المزود بشكل مستقل.')}</p><Button disabled={busy} variant="outline" onClick={()=>action('disconnect')}>{t('Confirm disconnect','تأكيد الفصل')}</Button><Button variant="ghost" onClick={()=>setConfirmDisconnect(false)}>{t('Cancel','إلغاء')}</Button></>:<Button variant="outline" onClick={()=>setConfirmDisconnect(true)}><Unplug size={15}/>{t('Disconnect','فصل الاتصال')}</Button>}</div>}
      </div>}
      {!!connection?.syncRuns.length&&<div className="sync-history"><h4><Clock3 size={15}/>{t('Sync history','سجل المزامنة')}</h4>{connection.syncRuns.map(run=><div key={run.id}><span className="subtle-tag">{status(run.status)}</span><span>{run.from.slice(0,10)} → {run.to.slice(0,10)}</span><strong>{run.records} {t('records','سجل')}</strong>{run.errorCode&&<small className="negative">{run.errorCode}</small>}</div>)}</div>}
    </section>}
    <SourceInsights summaries={data.summaries} ar={ar}/>
  </div>;
}
export function SourceInsights({summaries,ar}:{summaries:SourceSummary[];ar:boolean}){if(!summaries.length)return null;const t=(en:string,a:string)=>ar?a:en;const labels={grossSales:t('Gross order value','إجمالي قيمة الطلبات'),orders:t('Orders (all statuses)','الطلبات (جميع الحالات)'),adSpend:t('Ad spend','الإنفاق الإعلاني'),impressions:t('Impressions','مرات الظهور'),clicks:t('Clicks','النقرات'),sessions:t('Sessions','الجلسات'),conversions:t('Provider conversions','تحويلات المزود'),attributedRevenue:t('Attributed conversion value','قيمة التحويلات المنسوبة')};return <section className="panel connected-insights"><div className="panel-heading"><div><h3>{t('Connected source insights','رؤى المصادر المتصلة')}</h3><p>{t('Source totals remain separate from manual financial records. Currency and reporting dates are shown for every source.','تظل مجاميع المصادر منفصلة عن السجلات المالية اليدوية، مع توضيح العملة وفترة كل مصدر.')}</p></div></div>{summaries.map(s=><div className="source-summary" key={s.provider+s.currency}><div className="source-summary-title"><h4>{integrationCatalog.find(c=>c.id===s.provider)?.name??s.provider}</h4><span>{s.from} → {s.to} · {s.currency} · {s.timezone}</span></div><div className="source-values">{Object.entries(s.totals).map(([key,value])=><div key={key}><small>{labels[key as keyof typeof labels]}</small><strong>{value?.toLocaleString('en-US',{maximumFractionDigits:2})??'—'}</strong></div>)}</div><p>{s.notes.join(' ')}</p><small>{t('Last sync','آخر مزامنة')}: {new Date(s.lastSync).toLocaleString(ar?'ar-SA':'en-GB')}</small></div>)}</section>;}
