'use client';
import { useEffect,useState,type FormEvent } from 'react';
import { Bell,CheckCheck,ListTodo,ShieldCheck,Zap } from 'lucide-react';
import { Button } from './ui/button';
import { applyDemoOperation,emptyOperations,type OperationsView } from '@/modules/operations/demo';
import { operationInput,type Operation } from '@/modules/operations/service';
import type { DailyMetric } from '@/modules/metrics/engine';

export function OperationsHub({businessId,demo,token,ar,rows,initialTab='rules'}:{businessId:string;demo:boolean;token:string;ar:boolean;rows:DailyMetric[];initialTab?:'rules'|'tasks'|'alerts'}){
  const [tab,setTab]=useState<'rules'|'tasks'|'alerts'|'approvals'|'audit'>(initialTab),[data,setData]=useState<OperationsView>(emptyOperations),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
  const [decision,setDecision]=useState<{id:string;decision:'approve'|'reject'}|null>(null);
  const t=(en:string,arabic:string)=>ar?arabic:en,key=`dms-operations-demo-v1:${businessId}`;
  async function fetchState(){const response=await fetch(`/api/operations?businessId=${encodeURIComponent(businessId)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error);return result as OperationsView;}
  useEffect(()=>{let active=true;setReady(false);if(demo){try{const stored=localStorage.getItem(key);setData(stored?JSON.parse(stored):emptyOperations());}catch{setData(emptyOperations());}setReady(true);}else fetchState().then(result=>{if(active){setData(result);setReady(true);}}).catch(error=>{if(active)setNotice(error.message);});return()=>{active=false;};},[businessId,demo,token,key]);
  async function run(command:Operation){setBusy(true);setNotice('');try{operationInput.parse(command);if(demo){const next=applyDemoOperation(data,command,rows);localStorage.setItem(key,JSON.stringify(next));setData(next);}else{const response=await fetch('/api/operations',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({businessId,command})});const result=await response.json();if(!response.ok)throw Error(result.error);setData(await fetchState());}setNotice(t('Saved.','تم الحفظ.'));setDecision(null);return true;}catch(error){setNotice(error instanceof Error?error.message:t('Could not save.','تعذر الحفظ.'));return false;}finally{setBusy(false);}}
  async function taskSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form);const task={title:String(values.get('title')),priority:String(values.get('priority')) as 'normal'|'high'|'urgent',dueDate:String(values.get('dueDate'))||null};const request=values.get('approval')==='on';if(await run(request?{operation:'request_approval',task,reason:String(values.get('reason'))||t('Review proposed task','مراجعة المهمة المقترحة')}:{operation:'create_task',task}))form.reset();}
  async function ruleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form);const command=operationInput.parse({operation:'create_rule',rule:{name:values.get('name'),condition:{metric:values.get('metric'),operator:values.get('operator'),threshold:Number(values.get('threshold')),days:Number(values.get('days'))},action:values.get('action')}});if(await run(command))form.reset();}
  const label=(status:string)=>({open:t('Open','مفتوحة'),in_progress:t('In progress','قيد التنفيذ'),done:t('Done','مكتملة'),pending:t('Pending','بانتظار القرار'),executed:t('Executed','تم التنفيذ'),rejected:t('Rejected','مرفوضة'),normal:t('Normal','عادية'),high:t('High','مرتفعة'),urgent:t('Urgent','عاجلة')}[status]??status);
  return <section className="operations-hub">
    <div className="inline-note"><ShieldCheck size={20}/><span>{demo?t('Demo operations are saved in this browser. Rules evaluate the latest sample day.','العمليات التجريبية محفوظة في هذا المتصفح. تُفحص القواعد حتى آخر يوم تجريبي.'):t('Rules check completed days in your business timezone using the manual ledger.','تُفحص القواعد على الأيام المكتملة حسب توقيت النشاط وباستخدام السجل اليدوي.')}</span></div>
    <div className="ops-tabs" role="tablist" aria-label={t('Operations','العمليات')}>{([{id:'rules',en:'Rules',ar:'القواعد',icon:Zap},{id:'tasks',en:'Tasks',ar:'المهام',icon:ListTodo},{id:'alerts',en:'Saved alerts',ar:'التنبيهات المحفوظة',icon:Bell},{id:'approvals',en:'Approvals',ar:'الموافقات',icon:ShieldCheck},{id:'audit',en:'Activity',ar:'سجل النشاط',icon:CheckCheck}] as const).map(item=><button role="tab" aria-selected={tab===item.id} key={item.id} onClick={()=>{setTab(item.id);setDecision(null);}}><item.icon size={16}/>{item[ar?'ar':'en']}</button>)}</div>
    {notice&&<p className="inline-note" role="status">{notice}</p>}
    {!ready?<p>{t('Loading operations…','جاري تحميل العمليات…')}</p>:<>
    {tab==='tasks'&&<><section className="panel ops-panel"><h3>{t('Create a task','إنشاء مهمة')}</h3><form className="ops-form" onSubmit={taskSubmit}><label>{t('Task title','عنوان المهمة')}<input name="title" required maxLength={200}/></label><label>{t('Priority','الأولوية')}<select name="priority">{['normal','high','urgent'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>{t('Due date','تاريخ الاستحقاق')}<input name="dueDate" type="date"/></label><label className="ops-checkbox"><input name="approval" type="checkbox"/>{t('Request approval before creating','طلب الموافقة قبل الإنشاء')}</label><label>{t('Reason for approval','سبب طلب الموافقة')}<input name="reason" maxLength={1000}/></label><Button type="submit" disabled={busy||!data.canWrite}>{t('Save task request','حفظ طلب المهمة')}</Button></form></section><section className="panel ops-panel"><h3>{t('Task list','قائمة المهام')}</h3>{!data.tasks.length&&<p>{t('No tasks yet. Add one or convert a saved alert.','لا توجد مهام بعد. أضف مهمة أو حوّل تنبيهًا محفوظًا.')}</p>}{data.tasks.map(task=><article className="ops-row" key={task.id}><div><strong>{task.title}</strong><p>{label(task.priority)} · {task.dueAt?.slice(0,10)??t('No due date','بدون موعد')}</p></div><select aria-label={`${t('Task status','حالة المهمة')}: ${task.title}`} value={task.status} disabled={busy||!data.canWrite} onChange={e=>run({operation:'task_status',id:task.id,status:e.target.value as 'open'|'done'|'in_progress'})}>{['open','in_progress','done'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></article>)}</section></>}
    {tab==='rules'&&<><section className="panel ops-panel"><h3>{t('New automation rule','قاعدة أتمتة جديدة')}</h3><p>{t('Trigger once per rule and completed day. Every day in the window must meet the condition. Missing data never triggers a rule.','تشغيل واحد لكل قاعدة ويوم مكتمل. يجب تحقق الشرط في كل أيام المدة؛ البيانات الناقصة لا تُطلق القاعدة.')}</p><form className="ops-form" onSubmit={ruleSubmit}><label>{t('Rule name','اسم القاعدة')}<input name="name" required maxLength={120}/></label><label>{t('Metric','المؤشر')}<select name="metric"><option value="roas">{t('Blended ROAS','العائد المدمج')}</option><option value="profit">{t('Estimated profit','الربح التقديري')}</option><option value="revenue">{t('Revenue','الإيرادات')}</option><option value="orders">{t('Orders','الطلبات')}</option><option value="conversion">{t('Conversion %','التحويل %')}</option></select></label><label>{t('Condition','الشرط')}<select name="operator"><option value="lt">{t('Less than','أقل من')}</option><option value="gt">{t('Greater than','أكبر من')}</option></select></label><label>{t('Threshold','الحد')}<input name="threshold" type="number" min={-1e9} max={1e9} step="any" required defaultValue="1.5"/></label><label>{t('Consecutive days','الأيام المتتالية')}<input name="days" type="number" min="1" max="30" required defaultValue="1"/></label><label>{t('Action','الإجراء')}<select name="action"><option value="alert">{t('Create alert','إنشاء تنبيه')}</option><option value="task_approval">{t('Alert + task approval','تنبيه + طلب موافقة على مهمة')}</option></select></label><Button disabled={busy||!data.canManage} type="submit">{t('Save disabled rule','حفظ القاعدة معطلة')}</Button></form></section><section className="panel ops-panel"><div className="ops-row"><h3>{t('Your rules','قواعدك')}</h3><Button variant="outline" disabled={busy||!data.canManage} onClick={()=>run({operation:'evaluate'})}>{t('Evaluate now','فحص الآن')}</Button></div>{!demo&&!data.workerConfigured&&<p>{t('Hourly evaluation needs REDIS_URL and npm run worker. Evaluate now works without Redis.','يتطلب الفحص كل ساعة REDIS_URL وتشغيل العامل. يعمل الفحص اليدوي دون Redis.')}</p>}{!data.rules.length&&<p>{t('Create your first rule above.','أنشئ أول قاعدة من النموذج أعلاه.')}</p>}{data.rules.map(rule=><article className="ops-row" key={rule.id}><div><strong>{rule.name}</strong><p>{rule.condition.metric} {rule.condition.operator==='lt'?'<':'>'} {rule.condition.threshold} · {rule.condition.days} {t('days','أيام')}</p>{rule.evaluations?.[0]&&<details><summary>{t('Latest evaluation evidence','أدلة آخر فحص')}</summary><pre>{JSON.stringify(rule.evaluations[0].evidence,null,2)}</pre></details>}</div><Button variant="outline" disabled={busy||!data.canManage} onClick={()=>run({operation:'toggle_rule',id:rule.id,enabled:!rule.enabled})}>{rule.enabled?t('Disable','تعطيل'):t('Enable','تفعيل')}</Button></article>)}</section></>}
    {tab==='alerts'&&<section className="panel ops-panel"><h3>{t('Saved automation alerts','تنبيهات الأتمتة المحفوظة')}</h3>{!data.alerts.length&&<p>{t('No saved alerts. Enable a rule and evaluate your data.','لا توجد تنبيهات محفوظة. فعّل قاعدة وافحص بياناتك.')}</p>}{data.alerts.map(alert=><article className="ops-row" key={alert.id}><div><strong>{alert.title}</strong><p>{alert.resolvedAt?t('Resolved','تمت المعالجة'):t('Needs review','يحتاج مراجعة')}</p><details><summary>{t('Evidence','الأدلة')}</summary><pre>{JSON.stringify(alert.evidence,null,2)}</pre></details></div><div className="ops-actions"><Button variant="outline" disabled={busy||!data.canWrite} onClick={()=>run({operation:'alert_task',id:alert.id})}>{t('Create task','إنشاء مهمة')}</Button>{!alert.resolvedAt&&<Button variant="outline" disabled={busy||!data.canWrite} onClick={()=>run({operation:'resolve_alert',id:alert.id})}>{t('Resolve','تمت المعالجة')}</Button>}</div></article>)}</section>}
    {tab==='approvals'&&<section className="panel ops-panel"><h3>{t('Review proposed tasks','مراجعة المهام المقترحة')}</h3><p>{t('Approval creates the exact task shown here. External campaign, budget and email actions have no executor yet. To change a request, reject it and submit a revised one.','الموافقة تنشئ المهمة المعروضة هنا. تنفيذ تغييرات الحملات والميزانيات والبريد غير متاح بعد. لتعديل الطلب، ارفضه وأرسل نسخة معدلة.')}</p>{!data.approvals.length&&<p>{t('No approval requests.','لا توجد طلبات موافقة.')}</p>}{data.approvals.map(request=><article className="ops-row" key={request.id}><div><strong>{request.immutablePayload.task.title}</strong><p>{label(request.status)} · {label(request.immutablePayload.task.priority)} · {request.immutablePayload.task.dueDate??'—'}</p><p>{request.immutablePayload.reason}</p></div>{request.status==='pending'&&<div className="ops-actions"><Button disabled={busy||!data.canManage} onClick={()=>setDecision({id:request.id,decision:'approve'})}>{t('Approve','موافقة')}</Button><Button variant="outline" disabled={busy||!data.canManage} onClick={()=>setDecision({id:request.id,decision:'reject'})}>{t('Reject','رفض')}</Button></div>}</article>)}{decision&&<form className="ops-form" onSubmit={event=>{event.preventDefault();const values=new FormData(event.currentTarget);run({operation:'decide',...decision,reason:String(values.get('decisionReason'))});}}><label>{t('Decision reason','سبب القرار')}<input name="decisionReason" required maxLength={1000}/></label><Button type="submit" disabled={busy}>{decision.decision==='approve'?t('Confirm approval and create task','تأكيد الموافقة وإنشاء المهمة'):t('Confirm rejection','تأكيد الرفض')}</Button><Button variant="ghost" type="button" onClick={()=>setDecision(null)}>{t('Cancel','إلغاء')}</Button></form>}</section>}
    {tab==='audit'&&<section className="panel ops-panel"><h3>{t('Operations activity','سجل العمليات')}</h3>{!data.audit.length&&<p>{t('No activity yet.','لا يوجد نشاط بعد.')}</p>}{data.audit.map(entry=><article className="ops-row" key={entry.id}><div><strong>{entry.action}</strong><p>{entry.reason}</p><small>{entry.result}</small></div><time>{new Date(entry.createdAt).toLocaleString(ar?'ar-SA':'en-GB')}</time></article>)}</section>}
    </>}
  </section>;
}
