import { ConnectorError,rangeSchema,sourceMetricSchema,type Credentials,type DateRange,type ReadConnector,type SyncResult } from '../types';
import { ProviderHttp,record,list,number,string } from '../http';
export class AnalyticsConnector implements ReadConnector {
  readonly provider='ga4' as const;
  constructor(private credentials:Credentials,private http=new ProviderHttp()){if(!credentials.accountId)throw new ConnectorError('CONFIGURATION');}
  private async report(range:DateRange,offset=0){return record(await this.http.json(`https://analyticsdata.googleapis.com/v1beta/properties/${this.credentials.accountId}:runReport`,{method:'POST',headers:{Authorization:`Bearer ${this.credentials.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({dateRanges:[{startDate:range.from,endDate:range.to}],dimensions:[{name:'date'}],metrics:[{name:'sessions'},{name:'ecommercePurchases'},{name:'purchaseRevenue'}],currencyCode:'SAR',limit:1000,offset,returnPropertyQuota:true})}));}
  async testConnection(){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);await this.report({from:yesterday,to:yesterday});}
  async fetchMetrics(input:DateRange):Promise<SyncResult>{const range=rangeSchema.parse(input),data=await this.report(range),rawRows=list(data.rows??[]);if(number(data.rowCount??0)>rawRows.length)throw new ConnectorError('IMPORT_LIMIT');const rows=rawRows.map(raw=>{const r=record(raw),d=string(record(list(r.dimensionValues)[0]).value),m=list(r.metricValues);return sourceMetricSchema.parse({date:`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}`,currency:'SAR',sessions:number(record(m[0]).value),conversions:number(record(m[1]).value),attributedRevenue:number(record(m[2]).value,true)});});
    const metadata=record(data.metadata??{});return{rows,records:rows.length,timezone:typeof metadata.timeZone==='string'?metadata.timeZone:'property timezone',notes:['GA4 purchase revenue is analytics attribution, not authoritative store revenue.','Currency requested as SAR using Google Analytics currency reporting.',...(metadata.subjectToThresholding?['Google applied data thresholds.']:[]),...(metadata.samplingMetadatas?['Google returned sampled data.']:[])]};}
}
